[[redirects]]
  from = "https://mailgo.netlify.com/*"
  to = "https://mailgo.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://mailgo.netlify.app/*"
  to = "https://mailgo.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://mailgo.manzinello.com/*"
  to = "https://mailgo.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://mailgo.js.org/*"
  to = "https://mailgo.dev/:splat"
  status = 301
  force = true